### ISSUE TITLE
Auch für einen Multiplus 2 24/3000 geeignet ?

### ISSUE THREAD

**Issue by eeprom23** [PepeTheFroggie/Victron-VE.Bus---esp32#1]
Hallo, ersteimal Lob für das tolle Projekt , hoffe es wird erfolgreich weiterentwickelt. 
meine Frage ist, ob es auch mit dem 24v multiplus 2 funktioniert ?!

**Comment by PepeTheFroggie** [comment]
Woher soll ich das wissen?
